# This file should have all the dependencies for development excluding the specific to the backends.
name: ibis-dev
channels:
  - conda-forge
dependencies:
  # Ibis hard dependencies
  - multipledispatch
  - numpy
  - pandas
  - pytz
  - regex
  - toolz

  # Ibis soft dependencies
  # TODO This section is probably not very accurate right now (some dependencies should probably be in the backends files)
  - sqlalchemy
  - dask
  - graphviz
  - openjdk=8
  - pytables
  - python-graphviz>=0.14, <=0.15
  - python-hdfs

  # Dev tools
  - asv
  - black=19.10b0
  - click
  - conda-build # feedstock
  - cmake
  - flake8
  - flake8-comprehensions
  - isort
  - jinja2
  - mypy
  - plumbum
  - pre-commit
  - pydocstyle
  - pygit2 # dev/genrelease.py
  - pytest
  - pytest-cov
  - pytest-mock
  - ruamel.yaml # feedstock
  - libiconv>=1.15  # bug in repo2docker, see https://github.com/jupyter/repo2docker/issues/758
  - xorg-libxpm
  - xorg-libxrender

  # Release
  - twine
  - wheel
  - conda-smithy

  # Docs
  - ipython
  - jupyter
  - matplotlib
  - nbconvert
  - nbsphinx
  - nomkl
  - pyarrow>=0.12 # must pin again otherwise strange things happen
  - semantic_version=2.6 # https://github.com/ibis-project/ibis/issues/2027
  - sphinx
  - sphinx-releases
  - sphinx_rtd_theme
  - pip
  - pip:
    - pysuerga
